### ISSUE TITLE
SKL: Unable to complete full Deqp run.

### ISSUE THREAD

**Issue by kalyankondapally** [intel/external-mesa#3]
Deqp run doesnt complete as we crash while running EGL tests:

11-06 14:16:04 I/ConsoleReporter: [627/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_context.gles1_gles2_vg#other pass
11-06 14:16:04 I/ConsoleReporter: [628/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb565_window pass
11-06 14:16:04 I/ConsoleReporter: [629/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb565_pixmap pass
11-06 14:16:08 I/ConsoleReporter: [630/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb565_pbuffer fail: === with config {glformat=rgba8888d24s8ms0,rotation=unspecified,surfacetype=window} ===
Crash: Incomplete test log
11-06 14:16:09 I/ConsoleReporter: [631/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb888_window pass
11-06 14:16:09 I/ConsoleReporter: [632/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb888_pixmap pass
11-06 14:16:16 I/ConsoleReporter: [633/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgb888_pbuffer fail: === with config {glformat=rgba8888d24s8ms0,rotation=unspecified,surfacetype=window} ===
Crash: Incomplete test log
11-06 14:16:17 I/ConsoleReporter: [634/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba4444_window pass
11-06 14:16:20 I/ConsoleReporter: [635/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba4444_pixmap pass
11-06 14:16:20 I/ConsoleReporter: [636/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba4444_pbuffer pass
11-06 14:16:23 I/ConsoleReporter: [637/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba5551_window pass
11-06 14:16:23 I/ConsoleReporter: [638/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba5551_pixmap pass
11-06 14:16:23 I/ConsoleReporter: [639/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba8888_window pass
11-06 14:16:23 I/ConsoleReporter: [640/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba8888_pixmap pass
11-06 14:16:27 I/ConsoleReporter: [641/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#rgba8888_pbuffer fail: === with config {glformat=rgba8888d24s8ms0,rotation=unspecified,surfacetype=window} ===
Crash: Incomplete test log
11-06 14:16:28 I/ConsoleReporter: [642/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles1#other pass
11-06 14:16:28 I/ConsoleReporter: [643/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb565_window pass
11-06 14:16:28 I/ConsoleReporter: [644/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb565_pixmap pass
11-06 14:16:32 I/ConsoleReporter: [645/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb565_pbuffer fail: === with config {glformat=rgba8888d24s8ms0,rotation=unspecified,surfacetype=window} ===
Crash: Incomplete test log
11-06 14:16:34 I/ConsoleReporter: [646/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb888_window pass
11-06 14:16:34 I/ConsoleReporter: [647/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb888_pixmap pass
11-06 14:16:38 I/ConsoleReporter: [648/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgb888_pbuffer fail: === with config {glformat=rgba8888d24s8ms0,rotation=unspecified,surfacetype=window} ===
Crash: Incomplete test log
11-06 14:16:39 I/ConsoleReporter: [649/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba4444_window pass
11-06 14:16:39 I/ConsoleReporter: [650/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba4444_pixmap pass
11-06 14:16:39 I/ConsoleReporter: [651/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba4444_pbuffer pass
11-06 14:16:39 I/ConsoleReporter: [652/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba5551_window pass
11-06 14:16:39 I/ConsoleReporter: [653/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba5551_pixmap pass
11-06 14:16:42 I/ConsoleReporter: [654/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba8888_window pass
11-06 14:16:42 I/ConsoleReporter: [655/3522 x86_64 CtsDeqpTestCases 192.168.1.10:5555] dEQP-EGL.functional.color_clears.multi_thread.gles2#rgba8888_pixmap pass
11-06 14:16:47 W/DeqpTestRunner: ADB link failed, retrying after a cooldown period
11-06 14:16:53 W/AndroidNativeDevice: AdbCommandRejectedException (device not found) when attempting shell ps | grep com.drawelements on device 192.168.1.10:5555
11-06 14:18:00 W/DeqpTestRunner: ADB link failed, trying to recover
11-06 14:19:11 W/DeqpTestRunner: ADB link failed after recovery, rebooting device
11-06 14:19:11 W/AndroidNativeDevice: AdbCommandRejectedException (device not found) when attempting reboot on device 192.168.1.10:5555
11-06 14:20:21 W/DeqpTestRunner: Cannot recover ADB connection
11-06 14:20:21 W/TestInvocation: Invocation did not complete due to device 192.168.1.10:5555 becoming not available. Reason: link killed after reboot
11-06 14:20:21 W/ResultReporter: Invocation failed: com.android.tradefed.device.DeviceNotAvailableException: link killed after reboot
11-06 14:20:21 W/AndroidNativeDevice: AdbCommandRejectedException (device not found) when attempting shell ls "/sdcard/report-log-files/" on device 192.168.1.10:5555
11-06 14:20:22 W/AndroidNativeDevice: AdbCommandRejectedException (device not found) when attempting shell ls "/sdcard/report-log-files/" on device 192.168.1.10:5555
11-06 14:20:23 W/AndroidNativeDevice: AdbCommandRejectedException (device not found) when attempting shell ls "/sdcard/report-log-files/" on device 192.168.1.10:5555
11-06 14:20:24 E/ReportLogCollector: Caught exception during pull.
11-06 14:20:24 E/ReportLogCollector: Attempted shell ls "/sdcard/report-log-files/" multiple times on device 192.168.1.10:5555 without communication success. Aborting.
com.android.tradefed.device.DeviceUnresponsiveException: Attempted shell ls "/sdcard/report-log-files/" multiple times on device 192.168.1.10:5555 without communication success. Aborting.
    at com.android.tradefed.device.AndroidNativeDevice.performDeviceAction(AndroidNativeDevice.java:1550)
    at com.android.tradefed.device.AndroidNativeDevice.executeShellCommand(AndroidNativeDevice.java:525)
    at com.android.tradefed.device.AndroidNativeDevice.executeShellCommand(AndroidNativeDevice.java:565)
    at com.android.tradefed.device.AndroidNativeDevice.doesFileExist(AndroidNativeDevice.java:893)
    at com.android.compatibility.common.tradefed.targetprep.ReportLogCollector.pull(ReportLogCollector.java:119)
    at com.android.compatibility.common.tradefed.targetprep.ReportLogCollector.tearDown(ReportLogCollector.java:106)
    at com.android.tradefed.invoker.TestInvocation.doTeardown(TestInvocation.java:524)
    at com.android.tradefed.invoker.TestInvocation.performInvocation(TestInvocation.java:451)
    at com.android.tradefed.invoker.TestInvocation.invoke(TestInvocation.java:166)
    at com.android.tradefed.command.CommandScheduler$InvocationThread.run(CommandScheduler.java:471)

**Comment by kalyankondapally** [comment]
Fixed with adding pbuffer support.
