### ISSUE TITLE
[ww33]dEQP-VK.ubo.random.all_shared_buffer#48 failed on android

### ISSUE THREAD

**Issue by jennycao** [intel/external-mesa#90]
CTS version: 9.0_R1
Following test failed.
dEQP-VK.ubo.random.all_shared_buffer#48| fail (timeout)

**Comment by strassek** [comment]
Interesting, this timeout shows up on APL but not SKL.
Here are the relevant messages I see in the logs:
```
08-24 14:59:11.553  6061  6079 I dEQP    : 
08-24 14:59:11.553  6061  6079 I dEQP    : Test case 'dEQP-VK.ubo.random.all_shared_buffer.48'..
08-24 14:59:11.691  3095  4039 D vndksupport: Loading /vendor/lib64/hw/gralloc.project-celadon.so from current namespace instead of sphal namespace.
08-24 14:59:11.709  3095  4039 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
08-24 14:59:11.709  3095  4039 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
08-24 14:59:11.709  3095  4039 E libEGL  : eglSetBlobCacheFuncsANDROID resulted in an error: 0x300c
08-24 14:59:11.709  3095  4039 I OpenGLRenderer: Initialized EGL, version 1.4
08-24 14:59:11.709  3095  4039 D OpenGLRenderer: Swap behavior 2
08-24 14:59:12.642  3095  3618 D DhcpClient: Broadcasting DHCPDISCOVER
08-24 14:59:12.890  3095  4190 V BackupManagerConstants: getFullBackupRequiredNetworkType(...) returns 2
08-24 14:59:12.890  3095  4190 V BackupManagerConstants: getFullBackupRequireCharging(...) returns true
08-24 14:59:42.692  6061  6078 F dEQP    : Watchdog timer timeout for touch interval
08-24 14:59:42.716  3095  3170 W InputDispatcher: channel 'fc4708a com.drawelements.deqp/android.app.NativeActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
08-24 14:59:42.716  3095  3170 E InputDispatcher: channel 'fc4708a com.drawelements.deqp/android.app.NativeActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
08-24 14:59:42.717  3095  3579 I WindowManager: WIN DEATH: Window{fc4708a u0 com.drawelements.deqp/android.app.NativeActivity}
08-24 14:59:42.717  3095  3579 W InputDispatcher: Attempted to unregister already unregistered input channel 'fc4708a com.drawelements.deqp/android.app.NativeActivity (server)'
08-24 14:59:42.717  3095  3113 W libprocessgroup: kill(-6061, 9) failed: No such process
08-24 14:59:42.717  3095  3113 I libprocessgroup: Successfully killed process cgroup uid 10061 pid 6061 in 0ms
08-24 14:59:42.717  2942  2942 I Zygote  : Process 6061 exited due to signal (9)
08-24 14:59:42.717  3095  5042 I ActivityManager: Process com.drawelements.deqp:testercore (pid 6061) has died: fore TOP 
08-24 14:59:42.718  3095  5042 W ActivityManager: Force removing ActivityRecord{50708b8 u0 com.drawelements.deqp/android.app.NativeActivity t7}: app died, no saved state
08-24 14:59:42.719  3669  3669 D StatusBar: disable<e i a s b h r c s > disable2<q i n >
08-24 14:59:42.723  2962  3081 W SurfaceFlinger: Attempting to destroy on removed layer: AppWindowToken{36d59f6 token=Token{ef6f691 ActivityRecord{50708b8 u0 com.drawelements.deqp/android.app.NativeActivity t7}}}#0
08-24 14:59:42.734  3095  3118 W ActivityManager: setHasOverlayUi called on unknown pid: 6061
08-24 14:59:43.121  2987  3021 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-24 14:59:47.828  3095  3579 I ActivityManager: Force stopping com.drawelements.deqp appid=10061 user=0: finished inst
08-24 14:59:47.829  3095  6097 W Binder  : Outgoing transactions from this process must be FLAG_ONEWAY
08-24 14:59:47.829  3095  6097 W Binder  : java.lang.Throwable
08-24 14:59:47.829  3095  6097 W Binder  : 	at android.os.BinderProxy.transact(Binder.java:1114)
08-24 14:59:47.829  3095  6097 W Binder  : 	at android.app.IInstrumentationWatcher$Stub$Proxy.instrumentationFinished(IInstrumentationWatcher.java:164)
08-24 14:59:47.829  3095  6097 W Binder  : 	at com.android.server.am.InstrumentationReporter$MyThread.run(InstrumentationReporter.java:86)
08-24 14:59:47.829  3095  3579 I ActivityManager: Killing 6044:com.drawelements.deqp/u0a61 (adj 0): stop com.drawelements.deqp
```
I'll have to add some more printing to see what call it is hanging on.

**Comment by renchenglei** [comment]
With the same image, this issue could be reproduced on APL, but not on KBL.

**Comment by strassek** [comment]
I was able to determine that the test is hanging during pipeline creation - not a big surprise given how intensive that operation is. Tomorrow I will dive into the driver to find out exactly where we are spending time.

**Comment by tpalli** [comment]
This might be shader compile/link, KBL is much more powerful so it does not timeout.

**Comment by strassek** [comment]
Right, looks like we timeout while the vertex shader is getting compiled. It doesn't look like there is anything wrong going on here, this is just a particularly nasty shader. So we are either going to need to increase the timeout value or figure out how to optimize the compiler.

**Comment by renchenglei** [comment]
But this seems one regression since last mesa rebase, @jennycao please help fix me.

**Comment by renchenglei** [comment]
Sorry for the noise, this is not a regression. The regression should be dEQP-GLES31.functional.ssbo.layout.random.all_shared_buffer#23.

**Comment by jennycao** [comment]
this test are dropped from CTS 9.0_R2, so close this bug.
